event:
  url: 'https://event.misw.jp/c101/'
  image: 'images/og.webp'

join:
  url: 'https://x.com/misw_info/status/2039897989632909800'
  image: 'img/join-schedule.webp'

blog:
  url: 'https://blog.misw.jp/'

works:
  url: 'https://18dafcde6bdc7f4f399fe8197dd30da9.misw.jp/#works-frame'

jquery:
  url: 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js'

overview:
  a:
    name: '設立'
    data: '1969年4月16日'
  b:
    name: '部員数(2026年3月時点)'
    data: '77人 (内インカレ8人)'
  c:
    name: '活動時間'
    data: '週二回(曜日不定): 17:00～19:30<br />21:00～23:00'
  d:
    name: '活動場所'
    data: '早稲田大学 西早稲田キャンパス 52号館<br />早稲田大学 戸山キャンパス 学生会館 E927'
  e:
    name: '部室'
    data: '早稲田大学 戸山キャンパス 学生会館 E927'
  f:
    name: '会費(半期)'
    a:
      name: '新規入会'
      data: '2,000円'
    b:
      name: '継続会員'
      data: '4,000円'

kanbu:
  a:
    role: '幹事長'
    name: 'おいしいごはん'
    group: 'CG研'
    image: 'img/kanbu/0.webp'
  b:
    role: '副幹事長'
    name: 'Ichka'
    group: 'MIDI研'
    image: 'img/kanbu/1.webp'
  c:
    role: '会計'
    name: 'はる'
    group: 'CG研'
    image: 'img/kanbu/2.webp'
  d:
    role: 'プログラミング研会長'
    name: 'ほたる'
    group: 'プロ研'
    image: 'img/kanbu/3.webp'
  e:
    role: 'CG研会長'
    name: '一鶴'
    group: 'CG研'
    image: 'img/kanbu/4.webp'
  f:
    role: 'MIDI研会長'
    name: 'Uchiwax, IF'
    group: 'MIDI研'
    image: 'img/kanbu/5.webp'

footer:
  contact: 'メールアドレス: misw.info☆gmail.com(☆を@に直して送信してください)<br />Twitter(<a href="https://twitter.com/misw_info" target="_blank" rel="noopener noreferrer">@misw_info</a>)やInstagram(<a href="https://www.instagram.com/misw.info/" target="_blank" rel="noopener noreferrer">@misw.info</a>)のダイレクトメッセージにお送りいただくこともできます。'
  copyright: 'Copyright (c) 2018-2026, MIS.W（早稲田大学経営情報学会）All rights reserved.'
